# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2wE2QAPM4DQlIYyC7Zbs4SNU_uCACgX
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import LabelEncoder

# --- Configuration ---
st.set_page_config(page_title="Iris Species Predictor", layout="centered")

# --- Load Model and LabelEncoder ---
@st.cache_resource
def load_assets():
    """Loads the trained Decision Tree model and LabelEncoder."""
    try:
        # Assuming the model files are in a 'models' subdirectory
        with open('/content/drive/MyDrive/Colab Notebooks/model/DecisionTree_iris.pkl', 'rb') as model_file:
            model = pickle.load(model_file)

        with open('/content/drive/MyDrive/Colab Notebooks/model/DecisionTree_iris.pkl', 'rb') as le_file:
            le = pickle.load(le_file)

        return model, le
    except FileNotFoundError:
        st.error("Model files not found. Ensure 'DecisionTree_iris.pkl' and 'LabelEncoder_iris.pkl' are in the 'models' directory.")
        return None, None

model, le = load_assets()

# --- Application Title and Description ---
st.title("🌺 Iris Species Predictor")
st.markdown("""
    This app uses a pre-trained **Decision Tree Classifier** to predict the species of an Iris flower
    based on its sepal and petal measurements.
""")

if model is not None:
    # --- Sidebar for Input Features ---
    st.sidebar.header("Input Features")

    # Input sliders for the four features (using ranges observed in the Iris dataset)
    sepal_length = st.sidebar.slider('Sepal Length (cm)', 4.0, 8.0, 5.4)
    sepal_width = st.sidebar.slider('Sepal Width (cm)', 2.0, 4.5, 3.4)
    petal_length = st.sidebar.slider('Petal Length (cm)', 1.0, 7.0, 1.3)
    petal_width = st.sidebar.slider('Petal Width (cm)', 0.1, 2.6, 0.2)

    # Note: The notebook also uses the 'Id' column, which is usually dropped.
    # We must include it here if the model was trained with it.
    # From the notebook: x_train,x_test,y_train,y_test=train_test_split(df.drop("Species",axis=1), df["Species"], test_size=0.2)
    # The dataframe dropped 'Species' but KEPT 'Id'. We need a placeholder for 'Id'.
    # We'll use a constant 'Id=151' for the user's prediction.
    input_data = {
        'Id': [151], # Arbitrary ID not present in training data (max 150)
        'SepalLengthCm': [sepal_length],
        'SepalWidthCm': [sepal_width],
        'PetalLengthCm': [petal_length],
        'PetalWidthCm': [petal_width]
    }

    # Create the DataFrame for prediction
    features_df = pd.DataFrame(input_data)

    # --- Prediction Logic ---
    st.subheader("User Input Data")
    st.dataframe(features_df.drop('Id', axis=1), use_container_width=True)

    if st.button('Predict Species'):
        # 1. Make the prediction (outputs encoded label: 0, 1, or 2)
        prediction_encoded = model.predict(features_df)

        # 2. Decode the prediction (outputs the original species name)
        # We need the classes from the LabelEncoder: 0='Iris-setosa', 1='Iris-versicolor', 2='Iris-virginica'
        # The LabelEncoder's inverse_transform handles the array of prediction(s)
        prediction_species = le.inverse_transform(prediction_encoded)

        st.subheader("Prediction Result")
        st.success(f"The predicted Iris species is: **{prediction_species[0]}**")

        # Optional: Show prediction probabilities
        prediction_proba = model.predict_proba(features_df)
        proba_df = pd.DataFrame(
            prediction_proba,
            columns=le.classes_
        )
        st.subheader("Prediction Probability")
        st.dataframe(proba_df, use_container_width=True)

# --- End of Streamlit app ---